### ISSUE TITLE
GPU binary for .Net

### ISSUE THREAD

**Issue by gharibkhani** [rca22/LightGBM.Net#3]
Hi,

Would you please include GPU Binaries in the nuget package then Microsoft ML.net team would be able to add GPU support to their wrapper.

Thanks

**Comment by mjmckp** [comment]
Native binaries compiled for NVidia GPUs are in the nuget package, and I've also just added them to GitHub.  Note that in general you would need to replace these native binaries with versions compiled from source for the particular GPU architecture you are using, as per [https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-gpu-version](url)
