### ISSUE TITLE
Using LightGBM CLI Models in C# - Seeking Guidance

### ISSUE THREAD

**Issue by wil70** [rca22/LightGBM.Net#5]
Hello,

I have trained a model using LightGBM CLI, and I am interested in using this model from a C# program. Unfortunately, I haven't been able to find an example of how to do this. Could you please point me in the right direction or provide some guidance?

I assume the code for using the model in C# should resemble something like this:

```
Booster booster = new Booster(@"path to my model from LightGBM CLI");
double[] desiredOutput = null;
var inputData = LoadInputs(@"path to my testing data", out desiredOutput);
var prediction = booster.Predict(inputData);
Console.WriteLine("Prediction: " + prediction);
Console.ReadLine();

```
Your assistance is greatly appreciated.

Thanks,
Wil

**Comment by mjmckp** [comment]
Loading an externally trained model isn't possible at the moment, but should be fairly easy to add, I'll have a closer look on Friday and get back to you.

**Comment by wil70** [comment]
That is awesome, thanks a lot @mjmckp

**Comment by gharibkhani** [comment]
I have been doing this for years. I wrote my application in C#, I got my data from SQL. You get the exec file (both CPU and GPU) create a new process and call it. You can have all the logs and print them in your application. You can pass all the parameters as execution parameters or store them in a file and pass the config file to that process.

**Comment by wil70** [comment]
> I have been doing this for years. I wrote my application in C#, I got my data from SQL. You get the exec file (both CPU and GPU) create a new process and call it. You can have all the logs and print them in your application. You can pass all the parameters as execution parameters or store them in a file and pass the config file to that process.

Thanks @gharibkhani , if I understand well you start a LightGBM process from your c# app as a command line and read the result? if yes, then that can work but this will be too slow for my application, I can have many requests per minutes.

I would prefer a clean in memory api like @mjmckp proposed, or is working on, where I can load an extrenally trained model once and then call as many time, as fast as I want the predcition (ie. double[] results = booster.Predict(double[] input_data); ...and I guess you could also have double[][] results_array = booster.Predict(double[][] input_data_array);

@gharibkhani , you remind me this project https://github.com/fstandhartinger/LightGbmDotNet from Florian/@fstandhartinger

**Comment by gharibkhani** [comment]
Microsoft has implemented ML for lightGBM but the issue is, that they stopped supporting it af version 3.0. 
Performance-wise, I am using it for my production in the same way and it is fast enough. Remember that you are not training during the production. Getting a prediction from an existing model takes milliseconds.

**Comment by wil70** [comment]
Thanks @gharibkhani , you right it is fast, but I have a big model and starting a new process every time might be costly. 
Can you point me to the code for "Microsoft has implemented ML for lightGBM", I will try it out  - Thank you!

**Comment by gharibkhani** [comment]
ML.Net
https://dotnet.microsoft.com/en-us/apps/machinelearning-ai/ml-dotnet

**Comment by mjmckp** [comment]
Note that LightGBM.Net was created due to a large number of inefficiencies
and numerical bugs in the ML.Net wrapper for LightGBM, so use ML.Net with
caution. Unlike ML.Net, LightGBM.Net is rigorously tested for exact
consistency between the managed and unmanaged tree implementations.

**Comment by gharibkhani** [comment]
Thank you. I will give it a try

**Comment by wil70** [comment]
Yes, I've noticed a similar pattern, @mjmckp. 

Microsoft possesses remarkable technology, but they might need to invest more resources to refine and promote it effectively, especially ensuring it's production-ready. At times, they don't seem to give equal weight to the entire pipeline with their other technology. It's a bit perplexing.

@mjmckp, please do inform me once you have the missing part from what started this thread, like 'Loading an externally trained model and then run one to many predictions'. I'm keen to test it too.

Thanks a lot!
Wil

**Comment by mjmckp** [comment]
@wil70 I've just added the facility to load externally trained models from file, please see example usage here: https://github.com/rca22/LightGBM.Net/blob/cb295d86192a861dd7f29991e808899dd6f561c1/LightGBMNet.Test/TrainerTest.cs#L1024

Note that you can load the models from file, or from a string.

I've also updated the NuGet packages with these changes (new package version is 1.0.21).

Please let me know if that does what you need.

**Comment by gharibkhani** [comment]
> @wil70 I've just added the facility to load externally trained models from file, please see example usage here:
> 
> https://github.com/rca22/LightGBM.Net/blob/cb295d86192a861dd7f29991e808899dd6f561c1/LightGBMNet.Test/TrainerTest.cs#L1024
> 
> Note that you can load the models from file, or from a string.
> 
> I've also updated the NuGet packages with these changes (new package version is 1.0.21).
> 
> Please let me know if that does what you need.

Hopefully, I can find some time to help you add GPU to it as well.

**Comment by wil70** [comment]
Thank @mjmckp 
Awesome, yes it is working - Thank you!

I also was able to use 
```
        Booster booster = Booster.FromFile("my_model"); // this an take a few seconds for heavy model
        double[][] inputData = loadInput("my_data.csv");
        double[] prediction1_10 = booster.PredictForMat(Booster.PredictType.Normal, inputData[0], 0, -1); // this one takes **1.2 sec  per PredictForMat** call which is good.
```
Once the booster has the model, each call to PredictForMat take ~ **1.2 sec**  which is good.
GPU support would be awesome @gharibkhani!

Note:
I saw in PredictForMat**s**, it has a number of class limitations. I have more than 1 class, I will need to look into it.
```
            if (NumClasses != 1)
                throw new Exception("Call PredictForMatsMulti when NumClasses > 1");
```
 PredictForMat (wihtout the 's' at the end), doesn't have that limitation.


This is a great fast library!

Thank you again!

Wil

**Comment by mjmckp** [comment]
> Hopefully, I can find some time to help you add GPU to it as well.

@gharibkhani LightGBM.Net has GPU support:

1. Compile a version of the native DLLs with GPU support ([see instructions here](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-gpu-version)), then copy these over either the files found in the `native` folder (if building from source), or over the files in the `build\x64` folder (if using the NuGet package).
2. Set the DeviceType parameter to GPU.

**Comment by mjmckp** [comment]
@wil70 Good to hear.  It's probably cleaner to use the native or managed predictors created by the new `PredictorsFromFile` methods rather than directly calling PredictForMat(s) on the Booster object.

**Comment by gharibkhani** [comment]
It's awesome. Thanks
