### ISSUE TITLE
Multi-threaded access to the model

### ISSUE THREAD

**Issue by ToadstoolJam** [rca22/LightGBM.Net#6]
I've created a .NET Web API project and written an API handler that successfully calls Booster.PredictForMat(...).

I've taken great care to ensure that each call to the API gets access to a Booster instance that is guaranteed to only be used with that particular API client, i.e. using object pools to have short-term leases on instances of Booster.

Do I actually need to ensure that each client has its own Booster instance, or can I share a single Booster instance across all clients?

Having one instance would vastly improve the runtime performance of my API, but I need to be sure it's a safe thing to do.

**Comment by mjmckp** [comment]
@ToadstoolJam Calling Booster.PredictForMat is a thin wrapper around the underlying call to LGBM_BoosterPredictForMat on the native Booster object.  According to this thread https://github.com/microsoft/LightGBM/issues/666 the Booster object is thread safe, but only because it uses a lock.  Perhaps you could try using the managed version of the tree instead? That is thread-safe, provided you are only doing evaluation of the tree on each thread.

**Comment by ToadstoolJam** [comment]
Thanks @mjmckp.

Since I'm using .NET Web API, which I assume will run my code on a single thread for each invocation of my API endpoint, and I'm not doing my own thread management, I take it that I can call the PredictForMat(...) method safely on an instance of a LightGBMNet.Train.Booster class that is available inside a Singleton helper service.

I've had a look at the managed version of the tree in the LightGBMNet.Train.BinaryTrainer and LightGBMNet.Train.TrainerBase. Although I can see that the BinaryTrainer has a few useful features compared to a basic Booster (e.g. it covers training as well as model queries), I think the basic Booster is all I need for now. I'm loading models trained using the LightGBM CLI. 

I can't find any use of "lock" or "mutex" in the managed version in those two particular classes, but I have found "SHARED_LOCK(mutex_)" in the c_api.cpp file used by the LGBM_BoosterPredictForMat helper method...

https://github.com/microsoft/LightGBM/blob/master/src/c_api.cpp#L429C5-L429C24

I'll remove my object pool of Booster instances and try a single shared Booster instance.
